spring:
  cloud:
    sentinel:
      # 关闭控制台（本地简单使用)
      enabled: true
      web-context-unify: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/short-link?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
  data:
    redis:
      host: 192.168.106.130
      port: 6379
      password: 123321
      database: 2
      lettuce:
        pool:
          max-active: 20
          max-idle: 5
          min-idle: 2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 消息确认
    publisher-confirm-type: correlated
    publisher-returns: true
short-link:
  cache:
    expire-seconds: 86400
  domain: http://localhost:8080/api


logging:
  level:
    com.liu.shortlinkplatform: INFO
    root: WARN
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 7
      total-size-cap: 1GB
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
